name: bitcoin-prometheus
env:
  DOCKERHUB_IMAGE: wileyj/bitcoin
  DOCKERFILE: docker/Dockerfile
on:
  pull_request:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag to create (optional)'
        required: false

jobs:
  buildx:
    name: Bitcoin Core Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build: ["-prometheus"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set Vars
        run: echo "BTC_VERSION=$(cat docker/VERSION)" >> $GITHUB_ENV

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push ${{ env.BTC_VERSION }}
        uses: docker/build-push-action@v2
        with:
          file: ${{ env.DOCKERFILE }}
          build-args: |
            BTC_VERSION=${{ env.BTC_VERSION }}
          push: true
          tags: |
            ${{ env.DOCKERHUB_IMAGE }}:${{ env.BTC_VERSION }}${{ matrix.build }}

# jobs:
#   build-publish:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Set Vars
#         run: |
#           echo "BTC_VERSION=$(cat docker/VERSION)" >> $GITHUB_ENV

#       - name: Echo BTC Version
#         run: echo ${{env.BTC_VERSION}}

#       # - name: Build/Tag/Push Image
#       #   uses: docker/build-push-action@v1
#       #   with:
#       #     file: ${{ env.DOCKERFILE }}
#       #     repository: ${{ env.DOCKERHUB_IMAGE }}
#       #     username: ${{ secrets.DOCKERHUB_USERNAME }}
#       #     password: ${{ secrets.DOCKERHUB_PASSWORD }}
#       #     tags: ${{env.BTC_VERSION}}-prometheus
#       #     tag_with_ref: true
#       #     push: true
#       #     # Only push if (a tag was passed in) or (we're building a non-master branch which isn't a PR)
#       #     # push: ${{ github.event.inputs.tag != '' || (github.ref != 'refs/heads/master' && !contains(github.ref, 'refs/pull')) }}
