name: bitcoin-prometheus
env:
  DOCKERHUB_IMAGE: wileyj/bitcoin
  DOCKERFILE: docker/Dockerfile
on:
  pull_request:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag to create (optional)'
        required: false

jobs:
  buildx:
    name: Bitcoin Core Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build: ["-prometheus"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set Vars
        run: |
          echo "BTC_VERSION=$(cat docker/VERSION)" >> $GITHUB_ENV
          echo "MAJOR=$(grep \"define(_CLIENT_VERSION_MAJOR\" $FILE  | awk '{print $2}' | tr -d \))"
          echo "MINOR=$(grep "define(_CLIENT_VERSION_MINOR" $FILE  | awk '{print $2}' | tr -d \))" >> $GITHUB_ENV
          echo "BUILD=$(grep "define(_CLIENT_VERSION_BUILD" $FILE  | awk '{print $2}' | tr -d \))" >> $GITHUB_ENV
          echo "RC=$(grep "define(_CLIENT_VERSION_RC" $FILE  | awk '{print $2}' | tr -d \))" >> $GITHUB_ENV
      - name: Echo BTC Version
        run: |
          echo ${{env.BTC_VERSION}}
          echo ${{env.MAJOR}}
          echo ${{env.MINOR}}
          echo ${{env.BUILD}}
          echo ${{env.RC}}
      # - name: Login to Dockerhub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # - name: Build and Push ${{ env.BTC_VERSION }}
      #   uses: docker/build-push-action@v2
      #   with:
      #     file: ${{ env.DOCKERFILE }}
      #     build-args: |
      #       BTC_VERSION=${{ env.BTC_VERSION }}
      #     push: true
      #     tags: |
      #       ${{ env.DOCKERHUB_IMAGE }}:${{ env.BTC_VERSION }}${{ matrix.build }}
